apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version | replace "." "-"}}-canary
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Chart.Name }}-{{ .Chart.Version | replace "." "-" }}-canary
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}-{{ .Chart.Version | replace "." "-" }}-canary
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Chart.Version | replace "." "-" }}
          image: {{ .Values.canary.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 5003
          resources:
            limits:
              cpu: {{ .Values.canary.cpuLimit }}
              memory: {{ .Values.canary.memoryLimit }}