apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version | replace "." "-"}}-canary
spec:
  selector:
    name: {{ .Chart.Name }}-{{ .Chart.Version }}-canary-pod
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003